service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: Allow
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

  environment:
      PRODUCTS_TABLE: Products
      STOCKS_TABLE: Stocks
      SNS_ARN:
        Ref: SNSTopic

resources:
  Resources:
    SNSTopic: 
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription: 
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: Aliaksei_Palkhouski@epam.com
        Protocol: email
        TopicArn: 
          Ref: SNSTopic

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: product/available
          method: get
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: product/{productId}
          method: get
          request:
            parameters:
              paths:
                productId: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: product
          method: put
          cors: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:eu-west-1:073774905306:catalogItemsQueue

